#!/usr/bin/env bash

check_for_wip_commit() {
	echo "Checking for WIP Commits"
	while read local_ref local_sha remote_ref remote_sha
	do
		if [ "$local_sha" = $z40 ]
		then
			# Handle delete
			:
		else
			if [ "$remote_sha" = $z40 ]
			then
				# New branch, examine all commits
				range="$local_sha"
			else
				# Update to existing branch, examine new commits
				range="$remote_sha..$local_sha"
			fi

			# Check for WIP commit
			local commit=`git rev-list -n 1 --grep 'WIP' "$range"`
			if [ -n "$commit" ]
			then
				echo >&2 "Found WIP commit in $local_ref, not pushing"
				exit 1
			fi
		fi
	done
}

check_for_unTracked_files() {
    echo "Checking for untracked files"

    local unTrackedFiles=$(git ls-files --others --exclude-standard)

    if [ -n "$unTrackedFiles" ]
	then
		tput setaf 1; echo >&2 "Found Untracked files(s):"
		echo >&2 "$unTrackedFiles"
		echo >&2 "Commit or Stash file(s) before pushing to $remote"
		exit 1
	fi

}

pull() {
	echo "Applying latest changes from $remote"
	git pull --rebase

	if [ $? -ne 0 ]
	then
	  echo "Rebase failure, Cannot push to $remote" >&2
	  exit 1
	fi
}

run_tests() {
	echo "Running tests"
	./gradlew clean build

	if [ $? -ne 0 ]
	then
		echo "Tests failed, Cannot push to $remote" >&2
	  exit 1
	fi
}

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

check_for_wip_commit \
&& check_for_unTracked_files \
&& pull \
&& run_tests \
