#!/usr/bin/env bash

check_for_wip_commit() {
	echo "Checking for WIP Commits"
	while read local_ref local_sha remote_ref remote_sha
	do
		if [ "$local_sha" = $z40 ]
		then
			# Handle delete
			:
		else
			if [ "$remote_sha" = $z40 ]
			then
				# New branch, examine all commits
				range="$local_sha"
			else
				# Update to existing branch, examine new commits
				range="$remote_sha..$local_sha"
			fi

			# Check for WIP commit
			commit=`git rev-list -n 1 --grep 'WIP' "$range"`
			if [ -n "$commit" ]
			then
				echo >&2 "Found WIP commit in $local_ref, not pushing"
				exit 1
			fi
		fi
	done
}

pull() {
	echo "Performing git pull --rebase"
	git pull --rebase

	if [ $? -ne 0 ]
	then
	  echo "Rebase failure, Cannot push to $remote" >&2
	  exit 1
	fi
}

run_tests() {
	echo "Running tests"
	./gradlew clean build

	if [ $? -ne 0 ]
	then
		echo "Tests failed, Cannot push to $remote" >&2
	  exit 1
	fi
}

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

check_for_wip_commit \
&& pull \
&& run_tests \
